name: auto

on:
  schedule:
   - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      number:
        default: "10"
      max_workers:
        default: "1"
      ingest_to_oneapi:
        description: 'Ingest account tokens to OneAPI'
        type: boolean
        default: true
      upload_artifact:
        description: 'Upload account infos to artifact'
        type: boolean
        default: true

jobs:
  build:
    runs-on: windows-latest
    env:
      HIDE_ACCOUNT_INFO: "true"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run script for OneAPI
        run: |
          python3 ./cursor_register.py --oneapi --oneapi_url "http://api.0ha.top" --oneapi_token "c03f83f7dcf04ea3ab1cfe7196785c97" --oneapi_channel_url "http://alist.0ha.top" --number 10 --max_workers 5 
      - name: Run script for csv
        if: ${{ github.event.inputs.ingest_to_oneapi == 'false' && github.event.inputs.upload_artifact == 'true' }}
        run: |
          python3 ./cursor_register.py --number ${{ github.event.inputs.number }} --max_workers ${{ github.event.inputs.max_workers }}       
      - name: Upload csv files to artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Account Info"
          path: "*.csv"
          retention-days: 1
